version: "3"
services:
  server:
    image: debs2019challenge/benchmark-server
    ports:
      - "80:80"
    container_name: benchmark-server
    restart: always
    volumes:
      - /home/samba693/Documents/DEBS/debs2019/src/dataset/test/debs2019_dataset2/:/dataset

    networks:
          - bench

  client:
    container_name: client-app
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      BENCHMARK_SYSTEM_URL: 'server'

    depends_on:
      - server

    networks:
          - bench
    #tty: true


networks:
    bench: {}
